[build.environment]
NODE_VERSION = "21.7.3"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PNPM_VERSION = "9.7.1"

[build]
publish = "docs/.vuepress/dist"
command = """
npm install -g pnpm@${PNPM_VERSION}
pnpm install
pnpm run build
"""

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = '''
    max-age=31536000,
    immutable'''