[build.environment]
NODE_VERSION = "21.7.3"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[build]
publish = "docs/.vuepress/dist"
command = "pnpm run build"

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = '''
    max-age=31536000,
    immutable'''

[build.environment]
PNPM_VERSION = "9.7.1"

[build]
command = """
npm install -g pnpm@${PNPM_VERSION}
pnpm config set registry https://registry.npmmirror.com
pnpm install
pnpm run build
"""